const initial_board = [
  [
    { value: "", class: "green no-border", path: false },
    { value: "", class: "green no-border", path: false },
    { value: "", class: "green no-border", path: false },
    { value: "", class: "green no-border", path: false },
    { value: "", class: "green no-border", path: false },
    { value: "", class: "green no-border", path: false },
    { value: "", class: "", path: true },
    { value: "", class: "", path: true },
    { value: "", class: "", path: true },
    { value: "", class: "red no-border", path: false },
    { value: "", class: "red no-border", path: false },
    { value: "", class: "red no-border", path: false },
    { value: "", class: "red no-border", path: false },
    { value: "", class: "red no-border", path: false },
    { value: "", class: "red no-border", path: false },
  ],
  [
    { value: "", class: "green no-border", path: false },
    {
      value: "",
      class: " no-border initial-position-top-left green-dark",
      path: false,
    },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    {
      value: "",
      class: " no-border initial-position-top-right green-dark",
      path: false,
    },
    { value: "", class: "green no-border", path: false },
    { value: "", class: "", path: true },
    { value: "", class: "red", path: true },
    { value: "", class: "red", path: true },
    { value: "", class: "red no-border", path: false },
    {
      value: "",
      class: " no-border initial-position-top-left red-dark",
      path: false,
    },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    {
      value: "",
      class: " no-border initial-position-top-right red-dark",
      path: false,
    },
    { value: "", class: "red no-border", path: false },
  ],
  [
    { value: "", class: "green no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: "green no-border", path: false },
    { value: "", class: "", path: true },
    { value: "", class: "red", path: true },
    { value: "", class: "", path: true },
    { value: "", class: "red no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: "red no-border", path: false },
  ],
  [
    { value: "", class: "green no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: "green no-border", path: false },
    { value: "", class: "", path: true },
    { value: "", class: "red", path: true },
    { value: "", class: "", path: true },
    { value: "", class: "red no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: "red no-border", path: false },
  ],
  [
    { value: "", class: "green no-border", path: false },
    {
      value: "",
      class: " no-border initial-position-bottom-left green-dark",
      path: false,
    },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    {
      value: "",
      class: " no-border initial-position-bottom-right green-dark",
      path: false,
    },
    { value: "", class: "green no-border", path: false },
    { value: "", class: "", path: true },
    { value: "", class: "red", path: true },
    { value: "", class: "", path: true },
    { value: "", class: "red no-border", path: false },
    {
      value: "",
      class: " no-border initial-position-bottom-left red-dark",
      path: false,
    },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    {
      value: "",
      class: " no-border initial-position-bottom-right red-dark",
      path: false,
    },
    { value: "", class: "red no-border", path: false },
  ],
  [
    { value: "", class: "green no-border", path: false },
    { value: "", class: "green no-border", path: false },
    { value: "", class: "green no-border", path: false },
    { value: "", class: "green no-border", path: false },
    { value: "", class: "green no-border", path: false },
    { value: "", class: "green no-border", path: false },
    { value: "", class: "", path: true },
    { value: "", class: "red", path: true },
    { value: "", class: "", path: true },
    { value: "", class: "red no-border", path: false },
    { value: "", class: "red no-border", path: false },
    { value: "", class: "red no-border", path: false },
    { value: "", class: "red no-border", path: false },
    { value: "", class: "red no-border", path: false },
    { value: "", class: "red no-border", path: false },
  ],
  [
    { value: "", class: "", path: true },
    { value: "", class: "green", path: true },
    { value: "", class: "", path: true },
    { value: "", class: "", path: true },
    { value: "", class: "", path: true },
    { value: "", class: "", path: true },
    { value: "", class: " background-split-top-left no-border", path: false },
    { value: "", class: "red no-border", path: true },
    { value: "", class: " background-split-top-right no-border", path: false },
    { value: "", class: "", path: true },
    { value: "", class: "", path: true },
    { value: "", class: "", path: true },
    { value: "", class: "", path: true },
    { value: "", class: "", path: true },
    { value: "", class: "", path: true },
  ],
  [
    { value: "", class: "", path: true },
    { value: "", class: "green", path: true },
    { value: "", class: "green", path: true },
    { value: "", class: "green", path: true },
    { value: "", class: "green", path: true },
    { value: "", class: "green", path: true },
    { value: "", class: "green no-border", path: true },
    { value: "", class: " no-border ", path: false,child:[
      {value: "", class: "", path: false},
      {value: "", class: "", path: false},
      {value: "", class: "", path: false},
      {value: "", class: "", path: false},
    ] },
    { value: "", class: "yellow no-border", path: true },
    { value: "", class: "yellow", path: true },
    { value: "", class: "yellow", path: true },
    { value: "", class: "yellow", path: true },
    { value: "", class: "yellow", path: true },
    { value: "", class: "yellow", path: true },
    { value: "", class: "", path: true },
  ],
  [
    { value: "", class: "", path: true },
    { value: "", class: "", path: true },
    { value: "", class: "", path: true },
    { value: "", class: "", path: true },
    { value: "", class: "", path: true },
    { value: "", class: "", path: true },
    {
      value: "",
      class: " background-split-bottom-left no-border",
      path: false,
    },
    { value: "", class: "blue no-border", path: true },
    {
      value: "",
      class: " background-split-bottom-right no-border",
      path: false,
    },
    { value: "", class: "", path: true },
    { value: "", class: "", path: true },
    { value: "", class: "", path: true },
    { value: "", class: "", path: true },
    { value: "", class: "yellow", path: true },
    { value: "", class: "", path: true },
  ],
  [
    { value: "", class: "blue no-border", path: false },
    { value: "", class: "blue no-border", path: false },
    { value: "", class: "blue no-border", path: false },
    { value: "", class: "blue no-border", path: false },
    { value: "", class: "blue no-border", path: false },
    { value: "", class: "blue no-border", path: false },
    { value: "", class: "", path: true },
    { value: "", class: "blue", path: true },
    { value: "", class: "", path: true },
    { value: "", class: "yellow no-border", path: false },
    { value: "", class: "yellow no-border", path: false },
    { value: "", class: "yellow no-border", path: false },
    { value: "", class: "yellow no-border", path: false },
    { value: "", class: "yellow no-border", path: false },
    { value: "", class: "yellow no-border", path: false },
  ],
  [
    { value: "", class: "blue no-border", path: false },
    {
      value: "",
      class: " no-border initial-position-top-left blue-dark",
      path: false,
    },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    {
      value: "",
      class: " no-border initial-position-top-right blue-dark",
      path: false,
    },
    { value: "", class: "blue no-border", path: false },
    { value: "", class: "", path: true },
    { value: "", class: "blue", path: true },
    { value: "", class: "", path: true },
    { value: "", class: "yellow no-border", path: false },
    {
      value: "",
      class: " no-border initial-position-top-left yellow-dark",
      path: false,
    },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    {
      value: "",
      class: " no-border initial-position-top-right yellow-dark",
      path: false,
    },
    { value: "", class: "yellow no-border", path: false },
  ],
  [
    { value: "", class: "blue no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: "blue no-border", path: false },
    { value: "", class: "", path: true },
    { value: "", class: "blue", path: true },
    { value: "", class: "", path: true },
    { value: "", class: "yellow no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: "yellow no-border", path: false },
  ],
  [
    { value: "", class: "blue no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: "blue no-border", path: false },
    { value: "", class: "", path: true },
    { value: "", class: "blue", path: true },
    { value: "", class: "", path: true },
    { value: "", class: "yellow no-border no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: "yellow no-border", path: false },
  ],
  [
    { value: "", class: "blue no-border", path: false },
    {
      value: "",
      class: " no-border initial-position-bottom-left blue-dark",
      path: false,
    },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    {
      value: "",
      class: " no-border initial-position-bottom-right blue-dark",
      path: false,
    },
    { value: "", class: "blue no-border", path: false },
    { value: "", class: "blue", path: true },
    { value: "", class: "blue", path: true },
    { value: "", class: "", path: true },
    { value: "", class: "yellow no-border", path: false },
    {
      value: "",
      class: " no-border initial-position-bottom-left yellow-dark",
      path: false,
    },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    {
      value: "",
      class: " no-border initial-position-bottom-right yellow-dark",
      path: false,
    },
    { value: "", class: "yellow no-border", path: false },
  ],
  [
    { value: "", class: "blue no-border", path: false },
    { value: "", class: "blue no-border", path: false },
    { value: "", class: "blue no-border", path: false },
    { value: "", class: "blue no-border", path: false },
    { value: "", class: "blue no-border", path: false },
    { value: "", class: "blue no-border", path: false },
    { value: "", class: "", path: true },
    { value: "", class: "", path: true },
    { value: "", class: "", path: true },
    { value: "", class: "yellow no-border", path: false },
    { value: "", class: "yellow no-border", path: false },
    { value: "", class: "yellow no-border", path: false },
    { value: "", class: "yellow no-border", path: false },
    { value: "", class: "yellow no-border", path: false },
    { value: "", class: "yellow no-border", path: false },
  ],
];
export default initial_board;
