
const initial_board = [
  [
    { value: "", class: "green no-border", path: false },
    { value: "", class: "green no-border", path: false },
    { value: "", class: "green no-border", path: false },
    { value: "", class: "green no-border", path: false },
    { value: "", class: "green no-border", path: false },
    { value: "", class: "green no-border", path: false },
    { value: "", class: " path", path: true },
    { value: "", class: " path", path: true },
    { value: "", class: " path", path: true },
    { value: "", class: "red no-border", path: false },
    { value: "", class: "red no-border", path: false },
    { value: "", class: "red no-border", path: false },
    { value: "", class: "red no-border", path: false },
    { value: "", class: "red no-border", path: false },
    { value: "", class: "red no-border", path: false },
  ],
  [
    { value: "", class: "green no-border", path: false },
    {
      value: "",
      class: " no-border initial-position-top-left green-dark initial-pos",
      path: false,
    },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    {
      value: "",
      class: " no-border initial-position-top-right green-dark initial-pos",
      path: false,
    },
    { value: "", class: "green no-border", path: false },
    { value: "", class: " path", path: true },
    { value: "", class: "red path", path: true },
    { value: "", class: "red path", path: true },
    { value: "", class: "red no-border", path: false },
    {
      value: "",
      class: " no-border initial-position-top-left red-dark initial-pos",
      path: false,
    },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    {
      value: "",
      class: " no-border initial-position-top-right red-dark initial-pos",
      path: false,
    },
    { value: "", class: "red no-border", path: false },
  ],
  [
    { value: "", class: "green no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: "green no-border", path: false },
    { value: "", class: " path", path: true },
    { value: "", class: "red path", path: true },
    { value: "", class: " path", path: true },
    { value: "", class: "red no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: "red no-border", path: false },
  ],
  [
    { value: "", class: "green no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: "green no-border", path: false },
    { value: "", class: " path", path: true },
    { value: "", class: "red path", path: true },
    { value: "", class: " path", path: true },
    { value: "", class: "red no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: "red no-border", path: false },
  ],
  [
    { value: "", class: "green no-border", path: false },
    {
      value: "",
      class: " no-border initial-position-bottom-left green-dark initial-pos",
      path: false,
    },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    {
      value: "",
      class: " no-border initial-position-bottom-right green-dark initial-pos",
      path: false,
    },
    { value: "", class: "green no-border", path: false },
    { value: "", class: " path", path: true },
    { value: "", class: "red path", path: true },
    { value: "", class: " path", path: true },
    { value: "", class: "red no-border", path: false },
    {
      value: "",
      class: " no-border initial-position-bottom-left red-dark initial-pos",
      path: false,
    },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    {
      value: "",
      class: " no-border initial-position-bottom-right red-dark initial-pos",
      path: false,
    },
    { value: "", class: "red no-border", path: false },
  ],
  [
    { value: "", class: "green no-border", path: false },
    { value: "", class: "green no-border", path: false },
    { value: "", class: "green no-border", path: false },
    { value: "", class: "green no-border", path: false },
    { value: "", class: "green no-border", path: false },
    { value: "", class: "green no-border", path: false },
    { value: "", class: " path", path: true },
    { value: "", class: "red path", path: true },
    { value: "", class: " path", path: true },
    { value: "", class: "red no-border", path: false },
    { value: "", class: "red no-border", path: false },
    { value: "", class: "red no-border", path: false },
    { value: "", class: "red no-border", path: false },
    { value: "", class: "red no-border", path: false },
    { value: "", class: "red no-border", path: false },
  ],
  [
    { value: "", class: " path", path: true },
    { value: "", class: "green path", path: true },
    { value: "", class: " path", path: true },
    { value: "", class: " path", path: true },
    { value: "", class: " path", path: true },
    { value: "", class: " path", path: true },
    { value: "", class: " background-split-top-left no-border", path: false },
    { value: "", class: "red no-border path", path: true },
    { value: "", class: " background-split-top-right no-border", path: false },
    { value: "", class: " path", path: true },
    { value: "", class: " path", path: true },
    { value: "", class: " path", path: true },
    { value: "", class: " path", path: true },
    { value: "", class: " path", path: true },
    { value: "", class: " path", path: true },
  ],
  [
    { value: "", class: " path", path: true },
    { value: "", class: "green path", path: true },
    { value: "", class: "green path", path: true },
    { value: "", class: "green path", path: true },
    { value: "", class: "green path", path: true },
    { value: "", class: "green path", path: true },
    { value: "", class: "green no-border path", path: true },
    {
      value: "",
      class: " no-border centre-grid ",
      path: false,
      child: [
        { value: "", class: "background-split-top-left", path: false },
        { value: "", class: "background-split-top-right", path: false },
        { value: "", class: "background-split-bottom-left", path: false },
        { value: "", class: "background-split-bottom-right", path: false },
      ],
    },
    { value: "", class: "yellow no-border path", path: true },
    { value: "", class: "yellow path", path: true },
    { value: "", class: "yellow path", path: true },
    { value: "", class: "yellow path", path: true },
    { value: "", class: "yellow path", path: true },
    { value: "", class: "yellow path", path: true },
    { value: "", class: " path", path: true },
  ],
  [
    { value: "", class: " path", path: true },
    { value: "", class: " path", path: true },
    { value: "", class: " path", path: true },
    { value: "", class: " path", path: true },
    { value: "", class: " path", path: true },
    { value: "", class: " path", path: true },
    {
      value: "",
      class: " background-split-bottom-left no-border",
      path: false,
    },
    { value: "", class: "blue no-border path", path: true },
    {
      value: "",
      class: " background-split-bottom-right no-border",
      path: false,
    },
    { value: "", class: " path", path: true },
    { value: "", class: " path", path: true },
    { value: "", class: " path", path: true },
    { value: "", class: " path", path: true },
    { value: "", class: "yellow path", path: true },
    { value: "", class: " path", path: true },
  ],
  [
    { value: "", class: "blue no-border", path: false },
    { value: "", class: "blue no-border", path: false },
    { value: "", class: "blue no-border", path: false },
    { value: "", class: "blue no-border", path: false },
    { value: "", class: "blue no-border", path: false },
    { value: "", class: "blue no-border", path: false },
    { value: "", class: " path", path: true },
    { value: "", class: "blue path", path: true },
    { value: "", class: " path", path: true },
    { value: "", class: "yellow no-border", path: false },
    { value: "", class: "yellow no-border", path: false },
    { value: "", class: "yellow no-border", path: false },
    { value: "", class: "yellow no-border", path: false },
    { value: "", class: "yellow no-border", path: false },
    { value: "", class: "yellow no-border", path: false },
  ],
  [
    { value: "", class: "blue no-border", path: false },
    {
      value: "",
      class: " no-border initial-position-top-left blue-dark initial-pos",
      path: false,
    },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    {
      value: "",
      class: " no-border initial-position-top-right blue-dark initial-pos",
      path: false,
    },
    { value: "", class: "blue no-border", path: false },
    { value: "", class: " path", path: true },
    { value: "", class: "blue path", path: true },
    { value: "", class: " path", path: true },
    { value: "", class: "yellow no-border", path: false },
    {
      value: "",
      class: " no-border initial-position-top-left yellow-dark initial-pos",
      path: false,
    },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    {
      value: "",
      class: " no-border initial-position-top-right yellow-dark initial-pos",
      path: false,
    },
    { value: "", class: "yellow no-border", path: false },
  ],
  [
    { value: "", class: "blue no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: "blue no-border", path: false },
    { value: "", class: " path", path: true },
    { value: "", class: "blue path", path: true },
    { value: "", class: " path", path: true },
    { value: "", class: "yellow no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: "yellow no-border", path: false },
  ],
  [
    { value: "", class: "blue no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: "blue no-border", path: false },
    { value: "", class: " path", path: true },
    { value: "", class: "blue path", path: true },
    { value: "", class: " path", path: true },
    { value: "", class: "yellow no-border no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    { value: "", class: "yellow no-border", path: false },
  ],
  [
    { value: "", class: "blue no-border", path: false },
    {
      value: "",
      class: " no-border initial-position-bottom-left blue-dark initial-pos",
      path: false,
    },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    {
      value: "",
      class: " no-border initial-position-bottom-right blue-dark initial-pos",
      path: false,
    },
    { value: "", class: "blue no-border", path: false },
    { value: "", class: "blue path", path: true },
    { value: "", class: "blue path", path: true },
    { value: "", class: " path", path: true },
    { value: "", class: "yellow no-border", path: false },
    {
      value: "",
      class: " no-border initial-position-bottom-left yellow-dark initial-pos",
      path: false,
    },
    { value: "", class: " no-border", path: false },
    { value: "", class: " no-border", path: false },
    {
      value: "",
      class: " no-border initial-position-bottom-right yellow-dark initial-pos",
      path: false,
    },
    { value: "", class: "yellow no-border", path: false },
  ],
  [
    { value: "", class: "blue no-border", path: false },
    { value: "", class: "blue no-border", path: false },
    { value: "", class: "blue no-border", path: false },
    { value: "", class: "blue no-border", path: false },
    { value: "", class: "blue no-border", path: false },
    { value: "", class: "blue no-border", path: false },
    { value: "", class: " path", path: true },
    { value: "", class: " path", path: true },
    { value: "", class: " path", path: true },
    { value: "", class: "yellow no-border", path: false },
    { value: "", class: "yellow no-border", path: false },
    { value: "", class: "yellow no-border", path: false },
    { value: "", class: "yellow no-border", path: false },
    { value: "", class: "yellow no-border", path: false },
    { value: "", class: "yellow no-border", path: false },
  ],
];
export default initial_board


